<a href="https://colab.research.google.com/github/Mohamad-Selawy/Data-Analysis/blob/main/Data%20Analysis/Level%201/1_Pandas_Essentials_%26_Data_Ingestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Introduction to Pandas

Pandas is a powerful Python library used for working with data in an easy and flexible way. It helps you analyze, clean, and manipulate data quickly, making it one of the most important tools in Data Science.

Think of Pandas as Excel inside Python—but much more powerful and automated.

## 🚀 Why do we use Pandas?

Pandas makes it easy to:

*   Load data from files (CSV, Excel, JSON, etc.)
*   Clean messy data (missing values, duplicates, errors)
*   Analyze and explore data
*   Transform and reshape data
*   Perform statistical calculations
*   Work with time-based data (dates and trends)

## 🧱 Main Data Structures

Pandas is built on two main structures:

### 1. Series 📌

A Series is like a single column of data.

### 2. DataFrame 📊

A DataFrame is like a table (rows and columns), similar to Excel.

## 🔑 Key Features of Pandas

*   Handles missing data easily
*   Allows fast filtering and searching
*   Supports grouping and aggregation
*   Can merge and join datasets like databases
*   Works smoothly with large datasets

#Import Librarie

In [61]:
import pandas as pd

## Reading Data
We'll create small example files and read them using pandas.

In [62]:
# Read CSV
df_csv = pd.read_csv('sample_dataset.csv')
df_csv

    ID     Name  Age Department  Salary    JoinDate Gender  HasCar
0    1    Alice   25         HR   50000  2021-03-15      F       0
1    2      Bob   30         IT   60000  2020-08-21      M       0
2    3  Charlie   28    Finance   55000  2019-11-05      M       1
3    4    Diana   35  Marketing   70000  2018-07-10      F       0
4    5    Ethan   40         IT   80000  2017-02-25      M       0
5    6    Fiona   26         HR   52000  2022-01-18      F       1
6    7   George   32    Finance   57000  2021-06-14      M       0
7    8   Hannah   29  Marketing   71000  2020-09-10      F       1
8    9      Ian   31         IT   62000  2019-03-20      M       1
9   10     Jane   27         HR   53000  2022-04-11      F       0
10  11    Kevin   33    Finance   58000  2020-12-01      M       1
11  12    Laura   34  Marketing   73000  2018-06-06      F       1
12  13     Mike   36         IT   64000  2021-07-19      M       1
13  14     Nina   24         HR   51000  2022-02-28      F       0
14  15    Oscar   38    Finance   59000  2020-05-15      M       1
15  16    Paula   45  Marketing   74000  2017-11-09      F       0
16  17    Quinn   23         IT   66000  2023-03-23      M       1
17  18   Rachel   37         HR   54000  2021-09-30      F       0
18  19    Steve   41    Finance   60000  2016-01-15      M       0
19  20     Tina   22  Marketing   75000  2023-06-05      F       1

In [63]:
# Read Excel
df_excel = pd.read_excel('sample_dataset.xlsx')
df_excel

    ID     Name  Age Department  Salary    JoinDate Gender  HasCar
0    1    Alice   25         HR   50000  2021-03-15      F       0
1    2      Bob   30         IT   60000  2020-08-21      M       0
2    3  Charlie   28    Finance   55000  2019-11-05      M       1
3    4    Diana   35  Marketing   70000  2018-07-10      F       0
4    5    Ethan   40         IT   80000  2017-02-25      M       0
5    6    Fiona   26         HR   52000  2022-01-18      F       1
6    7   George   32    Finance   57000  2021-06-14      M       0
7    8   Hannah   29  Marketing   71000  2020-09-10      F       1
8    9      Ian   31         IT   62000  2019-03-20      M       1
9   10     Jane   27         HR   53000  2022-04-11      F       0
10  11    Kevin   33    Finance   58000  2020-12-01      M       1
11  12    Laura   34  Marketing   73000  2018-06-06      F       1
12  13     Mike   36         IT   64000  2021-07-19      M       1
13  14     Nina   24         HR   51000  2022-02-28      F       0
14  15    Oscar   38    Finance   59000  2020-05-15      M       1
15  16    Paula   45  Marketing   74000  2017-11-09      F       0
16  17    Quinn   23         IT   66000  2023-03-23      M       1
17  18   Rachel   37         HR   54000  2021-09-30      F       0
18  19    Steve   41    Finance   60000  2016-01-15      M       0
19  20     Tina   22  Marketing   75000  2023-06-05      F       1

In [64]:
# Read JSON
df_json = pd.read_json('sample_dataset.json')
df_json

    ID     Name  Age Department  Salary    JoinDate Gender  HasCar
0    1    Alice   25         HR   50000  2021-03-15      F       0
1    2      Bob   30         IT   60000  2020-08-21      M       0
2    3  Charlie   28    Finance   55000  2019-11-05      M       1
3    4    Diana   35  Marketing   70000  2018-07-10      F       0
4    5    Ethan   40         IT   80000  2017-02-25      M       0
5    6    Fiona   26         HR   52000  2022-01-18      F       1
6    7   George   32    Finance   57000  2021-06-14      M       0
7    8   Hannah   29  Marketing   71000  2020-09-10      F       1
8    9      Ian   31         IT   62000  2019-03-20      M       1
9   10     Jane   27         HR   53000  2022-04-11      F       0
10  11    Kevin   33    Finance   58000  2020-12-01      M       1
11  12    Laura   34  Marketing   73000  2018-06-06      F       1
12  13     Mike   36         IT   64000  2021-07-19      M       1
13  14     Nina   24         HR   51000  2022-02-28      F       0
14  15    Oscar   38    Finance   59000  2020-05-15      M       1
15  16    Paula   45  Marketing   74000  2017-11-09      F       0
16  17    Quinn   23         IT   66000  2023-03-23      M       1
17  18   Rachel   37         HR   54000  2021-09-30      F       0
18  19    Steve   41    Finance   60000  2016-01-15      M       0
19  20     Tina   22  Marketing   75000  2023-06-05      F       1

# Data Types & Conversions in Pandas
Understanding and managing data types correctly is essential for accurate computations, memory efficiency, and proper data analysis. Pandas supports various data types such as integers, floats, strings (objects), categorical data, and datetime formats.

###Common Pandas Data Types

| Data Type    | Description                               |
| ------------ | ----------------------------------------- |
| `int64`      | Integer numbers, typically for whole numbers. |
| `float64`    | Decimal numbers, used for numbers with fractional parts. |
| `object`     | Text/string data or mixed types (general Python objects). |
| `bool`       | Boolean values (`True`/`False`), for logical data. |
| `category`   | Categorical data, useful for finite and repeated values (e.g., genders, ratings). |
| `datetime64` | Date and time values, for working with temporal data. |

The `dtypes` attribute shows the data type of each column in your DataFrame. Understanding `dtypes` is crucial because it:

*   **Ensures correct operations:** You can't perform mathematical operations on text data.
*   **Optimizes memory usage:** Using the right data type can save memory.
*   **Helps identify issues:** Mismatched data types can indicate data quality problems.

In [65]:
df_csv.dtypes

ID             int64
Name          object
Age            int64
Department    object
Salary         int64
JoinDate      object
Gender        object
HasCar         int64
dtype: object

### Changing Data Types with `.astype()`

The `.astype()` method in Pandas is used to explicitly change the data type of a Series or DataFrame column. This is crucial for:

*   **Correct calculations:** Ensuring that numerical columns are treated as numbers, and dates as dates.
*   **Memory efficiency:** Storing data in the most appropriate format.
*   **Compatibility:** Matching data types for operations like merging or joining dataframes.

For example, if a column containing dates is loaded as an `object` (string), `df['column'].astype('datetime64[ns]')` will convert it into a proper datetime format, allowing for time-series analysis.

In [66]:
# Convert 'JoinDate' to datetime type
df_csv['JoinDate'] = df_csv['JoinDate'].astype('datetime64[s]')

# Verify the change
df_csv.dtypes

ID                    int64
Name                 object
Age                   int64
Department           object
Salary                int64
JoinDate      datetime64[s]
Gender               object
HasCar                int64
dtype: object

### Convert String to Categorical (saves memory)

The `category` data type in Pandas is used for columns that contain a limited number of unique values, which are often repeated many times. Examples include 'Yes'/'No', 'Male'/'Female', or colors like 'Red'/'Green'/'Blue'.

**Key benefits of using `category` data type:**

*   **Memory Efficiency:** For columns with many repeated values, storing them as categorical types can significantly reduce memory usage compared to storing them as `object` (string) types.
*   **Performance:** Some operations on categorical data can be faster than on object data, especially when sorting or performing certain statistical computations.

In the example, the 'Gender' column was converted to `category` because it only contains 'F' and 'M', which are finite and repeated values. This is a good practice for such columns.

In [67]:
df_csv['Gender'] = df_csv['Gender'].astype('category')
df_csv['Gender']

0     F
1     M
2     M
3     F
4     M
5     F
6     M
7     F
8     M
9     F
10    M
11    F
12    M
13    F
14    M
15    F
16    M
17    F
18    M
19    F
Name: Gender, dtype: category
Categories (2, object): ['F', 'M']

### Boolean Data Type

The `bool` data type stores `True` or `False` values. It's often used for flags or indicators, like our `HasCar` column, where `1` can represent `True` and `0` can represent `False`. Converting such columns to `bool` can make the data more semantically clear and sometimes more memory-efficient.

In [68]:
# Convert 'HasCar' to boolean type
df_csv['HasCar'] = df_csv['HasCar'].astype('bool')

# Verify the change
df_csv.dtypes

ID                    int64
Name                 object
Age                   int64
Department           object
Salary                int64
JoinDate      datetime64[s]
Gender             category
HasCar                 bool
dtype: object