<a href="https://colab.research.google.com/github/Mohamad-Selawy/Data-Analysis/blob/main/Data%20Analysis/Level%201/3_Data_Transformation_%26_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Transformation & Feature Engineering in Pandas

## 1. Dataset Overview & Setup

This section covers the initial setup of our environment by importing necessary libraries and loading the dataset. We'll then perform a preliminary inspection of the data to understand its structure, types, and summary statistics.

### 1.1 Import Libraries

We start by importing `pandas` for data manipulation and `numpy` for numerical operations, which will be useful for vectorized calculations.

In [47]:
import pandas as pd
import numpy as np

### 1.2 Load Dataset

We will load the `Data_Selection_&_Filtering.csv` file into a pandas DataFrame. This DataFrame, named `df`, will be used for all subsequent examples and exercises.

In [48]:
df = pd.read_csv('/content/Data_Selection_&_Filtering.csv')

### 1.3 Inspect Data: `df.head()`

The `.head()` method displays the first 5 rows of the DataFrame, providing a quick look at the data structure and content.

In [49]:
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
0,101,Alice Smith,IT,26,Female,60278,22,New York,71
1,102,Bob Johnson,HR,32,Male,87849,6,London,94
2,103,Charlie Brown,Finance,57,Male,83428,5,Paris,78
3,104,Diana Prince,Marketing,47,Female,65282,26,Tokyo,86
4,105,Eve Adams,IT,42,Female,62734,17,Berlin,78

## 2. Sorting & Indexing

Sorting data allows us to arrange DataFrame rows based on the values in one or more columns or by the DataFrame's index. This is fundamental for organizing and analyzing data.

### 2.1 Sort by Column Values (`.sort_values()`)

Use `.sort_values()` to sort the DataFrame by the values of a specified column. You can sort in ascending (default) or descending order. Here, we'll sort the DataFrame by `Price` in descending order.

In [50]:
df_sorted_salary = df.sort_values(by='Salary', ascending=False)
display(df_sorted_salary.head())

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
5,106,Frank White,Sales,29,Male,115720,2,New York,78
17,118,Rachel Scott,HR,52,Female,111177,22,Paris,94
8,109,Ivy Davis,Marketing,36,Female,106375,28,Tokyo,92
18,119,Steve Turner,Marketing,27,Male,104756,19,Tokyo,91
19,120,Tina Wright,Sales,40,Female,103158,27,Berlin,74

### 2.2 Sort by Index (`.sort_index()`)

The `.sort_index()` method sorts the DataFrame by its index labels. First, we'll set `OrderID` as the index, then sort by it. If no index is set, it sorts by the default integer index.

In [51]:
df_indexed = df.set_index('EmployeeID').sort_index()
display(df_indexed.head())

,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
EmployeeID,,,,,,,,
101,Alice Smith,IT,26,Female,60278,22,New York,71
102,Bob Johnson,HR,32,Male,87849,6,London,94
103,Charlie Brown,Finance,57,Male,83428,5,Paris,78
104,Diana Prince,Marketing,47,Female,65282,26,Tokyo,86
105,Eve Adams,IT,42,Female,62734,17,Berlin,78

### 2.3 Practice Exercise: Sorting

**Exercise 2:** Sort the original `df` DataFrame by `Category` in ascending order, and then by `Quantity` in descending order. Display the first 10 rows of the result.

In [52]:
# Your code here
df_sorted_exercise = df.sort_values(by=['Department', 'Experience'], ascending=[True, False])
display(df_sorted_exercise.head(10))

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore
13,114,Noah Lewis,Finance,27,Male,88227,20,Tokyo,88
9,110,Jack Miller,Finance,28,Male,54566,8,Berlin,90
2,103,Charlie Brown,Finance,57,Male,83428,5,Paris,78
12,113,Mia Clark,HR,44,Female,57225,29,Paris,71
6,107,Grace Taylor,HR,56,Female,52436,28,London,85
17,118,Rachel Scott,HR,52,Female,111177,22,Paris,94
1,102,Bob Johnson,HR,32,Male,87849,6,London,94
0,101,Alice Smith,IT,26,Female,60278,22,New York,71
16,117,Quinn Baker,IT,25,Female,65307,21,London,75
4,105,Eve Adams,IT,42,Female,62734,17,Berlin,78

## 3. Feature Creation & Vectorization

Feature creation involves deriving new columns from existing ones. Vectorized operations and conditional logic are powerful tools to achieve this efficiently.

### 3.1 Deriving New Columns with Vectorized Operations

Vectorized operations apply an operation to an entire array or series at once, which is significantly faster than row-by-row operations. Here, we'll calculate an `Effective_Salary` by multiplying `Salary` with `PerformanceScore` (normalized).

In [ ]:
df['Effective_Salary'] = df['Salary'] * (df['PerformanceScore'] / 100)
display(df.head())

### 3.2 Conditional Feature Creation

In [ ]:
avg_effective_salary = df['Effective_Salary'].mean()
df['Performance_Segment'] = df['Effective_Salary'].apply(lambda x: 'High Performer' if x > avg_effective_salary else 'Standard Performer')
display(df.head())

### 3.3 Practice Exercise: Feature Creation

**Exercise 3:** Add a new column called `Discount_Eligible` to the `df` DataFrame. If an employee's `Experience` is greater than 10 and their `Salary` is less than 80000, set `Discount_Eligible` to 'Yes', otherwise 'No'. Display the `Department`, `Experience`, `Salary`, and `Discount_Eligible` columns for the first 10 rows.

In [ ]:
# Your code here
df['Discount_Eligible'] = df.apply(lambda row: 'Yes' if (row['Experience'] > 10) and (row['Salary'] < 80000) else 'No', axis=1)
display(df[['Department', 'Experience', 'Salary', 'Discount_Eligible']].head(10))

## 4. Applying Functions: `.apply()`, `.map()`, and `lambda`

These are versatile tools for applying custom logic or transformations to DataFrame Series or elements.

### 4.1 Using `.apply()` with `lambda` for Conditional Logic

`.apply()` can be used with a `lambda` function to define custom logic for creating new columns based on conditions or transformations. Here, we'll categorize products based on whether their `Price` is above or below the average price.

In [59]:
avg_salary = df['Salary'].mean()
df['Salary_Tier'] = df['Salary'].apply(lambda x: 'High' if x > avg_salary else 'Low')
display(df.head())

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore,Effective_Salary,Performance_Segment,Discount_Eligible,Salary_Tier
0,101,Alice Smith,IT,26,Female,60278,22,New York,71,42797.38,Standard Performer,Yes,Low
1,102,Bob Johnson,HR,32,Male,87849,6,London,94,82578.06,High Performer,No,High
2,103,Charlie Brown,Finance,57,Male,83428,5,Paris,78,65073.84,Standard Performer,No,High
3,104,Diana Prince,Marketing,47,Female,65282,26,Tokyo,86,56142.52,Standard Performer,Yes,Low
4,105,Eve Adams,IT,42,Female,62734,17,Berlin,78,48932.52,Standard Performer,Yes,Low

### 4.2 Using `.map()` for Value Substitution

`.map()` is highly efficient for substituting values in a Series based on a dictionary or another Series. It's ideal for one-to-one mappings. We'll map `Category` to broader `Category_Group` names.

In [60]:
department_mapping = {
    'IT': 'Tech Dept',
    'HR': 'Admin Dept',
    'Finance': 'Finance Dept',
    'Marketing': 'Sales & Marketing',
    'Sales': 'Sales & Marketing'
}
df['Department_Group'] = df['Department'].map(department_mapping).fillna('Other')
display(df.head())

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceScore,Effective_Salary,Performance_Segment,Discount_Eligible,Salary_Tier,Department_Group
0,101,Alice Smith,IT,26,Female,60278,22,New York,71,42797.38,Standard Performer,Yes,Low,Tech Dept
1,102,Bob Johnson,HR,32,Male,87849,6,London,94,82578.06,High Performer,No,High,Admin Dept
2,103,Charlie Brown,Finance,57,Male,83428,5,Paris,78,65073.84,Standard Performer,No,High,Finance Dept
3,104,Diana Prince,Marketing,47,Female,65282,26,Tokyo,86,56142.52,Standard Performer,Yes,Low,Sales & Marketing
4,105,Eve Adams,IT,42,Female,62734,17,Berlin,78,48932.52,Standard Performer,Yes,Low,Tech Dept

### 4.3 Practice Exercise: Applying Functions

**Exercise 4:**
1. Create a new column `Product_Description_Length` that contains the length of each `Product` name.
2. Create a dictionary to map `Region` to `Continent` (e.g., 'North', 'East' -> 'America', 'Europe', 'Asia'). Use `.map()` to add a new `Continent` column to the DataFrame. Fill any unmapped regions with 'Unknown'.

In [61]:
# Your code here
# 1. Create a new column Name_Length
df['Name_Length'] = df['Name'].apply(lambda x: len(x))

# 2. Create a dictionary to map City to Country (Example cities from the dataset: New York, London, Paris, Tokyo, Berlin)
city_to_country = {
    'New York': 'USA',
    'London': 'UK',
    'Paris': 'France',
    'Tokyo': 'Japan',
    'Berlin': 'Germany'
}
df['Country'] = df['City'].map(city_to_country).fillna('Unknown')
display(df[['Name', 'Name_Length', 'City', 'Country']].head())

            Name  Name_Length      City  Country
0    Alice Smith           11  New York      USA
1    Bob Johnson           11    London       UK
2  Charlie Brown           13     Paris   France
3   Diana Prince           12     Tokyo    Japan
4      Eve Adams            9    Berlin  Germany

## 5. Merging, Joining, and Concatenating

Merging, joining, and concatenating are essential operations for combining DataFrames, allowing you to integrate information from different sources based on common columns or by simply stacking them.

### 5.1 Merging DataFrames (`pd.merge()`)

`pd.merge()` is used to combine two DataFrames based on common columns (keys). It's similar to SQL joins and offers various types (inner, outer, left, right). Below, we'll demonstrate an inner merge.

In [68]:
# Create df_employees_subset from the main df
df_employees_subset = df[['EmployeeID', 'Name', 'Department']].head(5)

# Create a sample DataFrame with additional contact information for demonstration
df_contact_info = pd.DataFrame({
    'EmployeeID': [101, 103, 105, 106], # Include some IDs from df_employees_subset and some new ones
    'Email': ['alice.s@example.com', 'charlie.b@example.com', 'eve.a@example.com', 'frank.w@example.com'],
    'Phone': ['555-1001', '555-1003', '555-1005', '555-1006']
})

print("df_employees_subset (derived from main df):")
display(df_employees_subset)
print("\ndf_contact_info:")
display(df_contact_info)

# Perform an inner merge on 'EmployeeID'
# This will show only employees present in both DataFrames
merged_inner_df = pd.merge(df_employees_subset, df_contact_info, on='EmployeeID', how='inner')
print("\nInner Merged DataFrame (employees with contact info):")
display(merged_inner_df)

# Also demonstrate a left merge to include all employees and their contact info if available
merged_left_df = pd.merge(df_employees_subset, df_contact_info, on='EmployeeID', how='left')
print("\nLeft Merged DataFrame (all employees, with contact info where available):")
display(merged_left_df)

df_employees_subset (derived from main df):

   EmployeeID           Name Department
0         101    Alice Smith         IT
1         102    Bob Johnson         HR
2         103  Charlie Brown    Finance
3         104   Diana Prince  Marketing
4         105      Eve Adams         IT

df_contact_info:

   EmployeeID                  Email     Phone
0         101    alice.s@example.com  555-1001
1         103  charlie.b@example.com  555-1003
2         105      eve.a@example.com  555-1005
3         106    frank.w@example.com  555-1006

Inner Merged DataFrame (employees with contact info):

   EmployeeID           Name Department                  Email     Phone
0         101    Alice Smith         IT    alice.s@example.com  555-1001
1         103  Charlie Brown    Finance  charlie.b@example.com  555-1003
2         105      Eve Adams         IT      eve.a@example.com  555-1005

Left Merged DataFrame (all employees, with contact info where available):

   EmployeeID           Name Department                  Email     Phone
0         101    Alice Smith         IT    alice.s@example.com  555-1001
1         102    Bob Johnson         HR                    NaN       NaN
2         103  Charlie Brown    Finance  charlie.b@example.com  555-1003
3         104   Diana Prince  Marketing                    NaN       NaN
4         105      Eve Adams         IT      eve.a@example.com  555-1005

### 5.2 Concatenating DataFrames (`pd.concat()`)

`pd.concat()` stacks DataFrames either vertically (row-wise) or horizontally (column-wise) along an axis. It's used to append or stack multiple DataFrames directly.

In [66]:
# Create two sample DataFrames for demonstration
df_part1 = pd.DataFrame({
    'Name': ['Frank', 'Grace'],
    'Age': [30, 25]
})

df_part2 = pd.DataFrame({
    'Name': ['Harry', 'Ivy'],
    'Age': [35, 28]
})

print("df_part1:")
display(df_part1)
print("\ndf_part2:")
display(df_part2)

# Concatenate them vertically
concatenated_df = pd.concat([df_part1, df_part2], ignore_index=True)
print("\nVertically Concatenated DataFrame:")
display(concatenated_df)

df_part1:

    Name  Age
0  Frank   30
1  Grace   25

df_part2:

    Name  Age
0  Harry   35
1    Ivy   28

Vertically Concatenated DataFrame:

    Name  Age
0  Frank   30
1  Grace   25
2  Harry   35
3    Ivy   28

### 5.3 Practice Exercise: Merging & Concatenating

**Exercise 5:**
1. Create a new DataFrame `df_additional_info` with `EmployeeID` and a new column `Project` (e.g., 'Alpha', 'Beta', 'Gamma').
2. Perform a left merge of the original `df` DataFrame with `df_additional_info` on `EmployeeID`.
3. Display the first 5 rows of the resulting DataFrame.

In [67]:
# Your code here

## Summary Table

| Task                       | Method(s)                                    | Description                                                     |
| :------------------------- | :------------------------------------------- | :-------------------------------------------------------------- |
| **Sorting**                | `df.sort_values(by='col')`                   | Sorts DataFrame rows by column values.                          |
|                            | `df.sort_index()`                            | Sorts DataFrame rows by index labels.                           |
| **Feature Creation**       | `df['new'] = df['col'] * 5`                  | Vectorized arithmetic operations to create new columns.         |
| **Applying Functions**     | `df['col'].apply(lambda x: ...)`             | Applies a custom function (often lambda) element-wise to a Series. |
|                            | `df['col'].map(dictionary_or_series)`        | Substitutes each value in a Series with another based on a mapping. |